Index: sslscan-1.6/Makefile
===================================================================
--- sslscan-1.6.orig/Makefile	2008-01-22 07:43:54.000000000 +0000
+++ sslscan-1.6/Makefile	2008-01-22 07:44:35.000000000 +0000
@@ -7,7 +7,7 @@
 
 install:
 	cp sslscan $(BINPATH)
-	cp sslscan.1 $(MANPATH)man1
+	cp sslscan.1 $(MANPATH)/man1/
 
 uninstall:
 	rm -f $(BINPATH)sslscan
