Document: sslcat
Title: Debian sslcat Manual
Author: <insert document author here>
Abstract: This manual describes what sslcat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sslcat/sslcat.sgml.gz

Format: postscript
Files: /usr/share/doc/sslcat/sslcat.ps.gz

Format: text
Files: /usr/share/doc/sslcat/sslcat.text.gz

Format: HTML
Index: /usr/share/doc/sslcat/html/index.html
Files: /usr/share/doc/sslcat/html/*.html
